"""Create initial Imovel and Certidao tables

Revision ID: 1d7d51cb4bfb
Revises: 
Create Date: 2025-08-03 22:24:42.543864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1d7d51cb4bfb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imovel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cidade', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cep', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proprietario_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imovel_cidade'), 'imovel', ['cidade'], unique=False)
    op.create_index(op.f('ix_imovel_endereco'), 'imovel', ['endereco'], unique=False)
    op.create_index(op.f('ix_imovel_id'), 'imovel', ['id'], unique=False)
    op.create_index(op.f('ix_imovel_proprietario_id'), 'imovel', ['proprietario_id'], unique=False)
    op.create_table('certidao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('arquivo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('imovel_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['imovel_id'], ['imovel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certidao_id'), 'certidao', ['id'], unique=False)
    op.create_index(op.f('ix_certidao_imovel_id'), 'certidao', ['imovel_id'], unique=False)
    op.create_index(op.f('ix_certidao_status'), 'certidao', ['status'], unique=False)
    op.create_index(op.f('ix_certidao_tipo'), 'certidao', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certidao_tipo'), table_name='certidao')
    op.drop_index(op.f('ix_certidao_status'), table_name='certidao')
    op.drop_index(op.f('ix_certidao_imovel_id'), table_name='certidao')
    op.drop_index(op.f('ix_certidao_id'), table_name='certidao')
    op.drop_table('certidao')
    op.drop_index(op.f('ix_imovel_proprietario_id'), table_name='imovel')
    op.drop_index(op.f('ix_imovel_id'), table_name='imovel')
    op.drop_index(op.f('ix_imovel_endereco'), table_name='imovel')
    op.drop_index(op.f('ix_imovel_cidade'), table_name='imovel')
    op.drop_table('imovel')
    # ### end Alembic commands ###
